# Generated by Django 5.2.4 on 2025-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_index=True, max_length=20, unique=True)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=17, null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('authors', models.JSONField(default=list)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('published_date', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('categories', models.JSONField(default=list)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('small_thumbnail', models.URLField(blank=True, null=True)),
                ('preview_link', models.URLField(blank=True, null=True)),
                ('info_link', models.URLField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(blank=True, null=True)),
                ('maturity_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('found', models.BooleanField(default=False)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-search_time'],
            },
        ),
    ]
